<p class="section-text">Atualmente chamada de Hellinger sciencia®, a Constelação Familiar, como é comumente conhecida no Brasil, foi desenvolvida por Bert Hellinger. O trabalho de constelação atua na dimensão espiritual do ser humano, o que não quer dizer que atue a partir de uma perspectiva religiosa, mas sim da espiritualidade. Espiritualidade, por definição, significa tudo o que tem por objeto a vida espiritual. Assim, podemos compreender o espiritual como sendo uma dimensão do ser humano, assim como o biológico, o psicológico e o social.</p>

@if (isset($showAll) && $showAll)
    <p class="section-text">O conceito de Campo da Gestalt terapia, nos fala de um campo que se estabelece entre o organismo e o ambiente. Ao utilizar este conceito na Constelação Familiar, compreendemos que este campo também se estabelece entre pessoas, ampliando assim a ideia inicial, e oferecendo suporte teórico ao trabalho das constelações. No workshop de Constelação Familiar, o participante elege um tema para ser constelado e escolhe algumas pessoas do grupo para representarem os seus familiares. Por se tratar de um workshop, é comum que as pessoas não se conheçam e, portanto, não possuam informações umas das outras. Podemos assim sugerir que, o Campo que se estabelece no trabalho de Constelação Familiar é o que permite o acesso à informações tão pessoais, sem que o representante conheça a história da pessoa que está sendo constelada. Este trabalho também pode acontecer no consultório, onde a Constelação Familiar pode ser realizada com bonecos, que serão utilizados como os representantes nas situações que são trazidas pelo cliente.</p>

    <p class="section-text">A diferença do trabalho individual para o trabalho em grupo, é a quantidade de informações que emergem. Pois, como há vários participantes no workshop, temos diferentes pontos de vista de uma mesma situação. Já no trabalho individual, temos apenas o terapeuta e o cliente. De toda maneira, ambos são trabalhos que costumam apresentar resultados satisfatórios no que diz respeito à tomada de consciência que buscamos na psicoterapia. O objetivo das Constelações Familiares é compreender o emaranhado sistêmico (dinâmica dos sistemas familiares), e de que forma podemos liberar o fluxo de amor que fica bloqueado quando há algum conflito, exclusão, segredo, rompimento, etc. O constelador não é aquele que libera o fluxo de amor, pois o trabalho acontece no Campo que se forma entre os participantes e o constelador. Este, na verdade, é aquele que acompanha a evolução do trabalho, contribuindo para que os conflitos venham à tona e possam assim serem compreendidos e reparados, possibilitando a restauração do fluxo de amor.</p>

    <p class="section-text">
        Todos os participantes das Constelações Familiares se beneficiam do trabalho, sejam os que são constelados, os que participam como representantes, e também os que assistem. Tanto aqueles que participam como representantes, como os que assistem, muitas vezes se identificam com a história que está sendo constelada, é isso auxilia percepções de si, através do trabalho que está acontecendo. Se entendemos que um Campo comum se estabelece entre os participantes, fica claro que todos podem se beneficiar do trabalho, mesmo que não constelem a sua própria história.
    </p>

    <p class="section-text">
        Quando realizada por um profissional sério e capacitado, os resultados tendem a aparecer, trazendo à consciência compreensões da dinâmica familiar que antes eram ignoradas ou desconhecidas. Por ser um trabalho também psicoterapeutico, não é recomendado que seja feito apenas por curiosidade. É importante que o participante esteja em acompanhamento psicológico, já que os desdobramentos da Constelação Familiar podem acontecer ao longo de meses após o trabalho.
    </p>
@else
    <a href="/constelacoes" class="btn btn-theme-color">Leia mais...</a>
@endif
