<p class="section-text">Atualmente chamada de Hellinger sciencia®, a Constelação Familiar, como é comumente conhecida no Brasil, foi desenvolvida por Bert Hellinger e descrita por este como uma ciência aberta, ou seja, um conhecimento que ainda está em construção, em desenvolvimento. O trabalho de constelação atua na dimensão espiritual do ser humano, o que não quer dizer que atue a partir de uma perspectiva religiosa, mas sim da espiritualidade, que por definição significa tudo o que tem por objeto a vida espiritual. Sendo assim, podemos compreender o espiritual como sendo também uma dimensão do ser humano, assim como o biológico, o psicológico e o social.</p>

@if (isset($showAll) && $showAll)
    <p class="section-text">Há um conceito em Gestalt terapia que se adequa à constelação, oferecendo suporte teórico ao trabalho. O conceito de Campo nos diz que existe uma conexão entre pessoas e mundo, o que nos traz uma compreensão ampliada para o que acontece no trabalho das Constelações Familiares. Nos workshops de Constelações Familiares, o trabalho acontece em grupo, onde pessoas são utilizadas como representantes em situações trazidas pelo participante que está sendo constelado. Por se tratar de um workshop, é comum que as pessoas não se conheçam e, portanto, não possuam informações umas das outras. Podemos assim sugerir que o Campo que se estabelece no trabalho de Constelações Familiares é o que permite o acesso a informações tão pessoais sem que o participante conheça a história que está sendo trabalhada. Já no atendimento psicoterapêutico individual, o trabalho de constelação pode acontecer com bonecos, que serão utilizados como representantes de pessoas ou elementos nas situações que são trazidas pelo cliente.</p>

    <p class="section-text">A diferença do trabalho individual para o trabalho em grupo é a quantidade de informações de surgem, já que, quando há vários participantes, temos diferentes pontos de vista de uma mesma situação, enquanto que no individual temos apenas o terapeuta e o cliente. De toda maneira ambos são trabalhos que costumam apresentar resultados satisfatórios no que diz respeito à tomada de consciência que buscamos na psicoterapia. O objetivo das Constelações Familiares é compreender o emaranhado sistêmico (dinâmica dos sistemas familiares) e de que forma podemos liberar o fluxo de amor (energia vital humana) que fica bloqueado quando há algum conflito, exclusão, segredo, rompimento, etc. O constelados não é aquele que libera o fluxo de amor, pois o trabalho acontece no Campo que se forma entre os participantes e o constelados, este, na verdade, é aquele que acompanha a evolução do trabalho, contribuindo para que os conflitos venham à tona e possam assim serem compreendidos possibilitando a restauração do fluxo de amor.</p>

    <p class="section-text">O trabalho nas constelações familiares acontece com todos os participantes, sejam os que são constelados, os participam como representantes, e também os que assistem. Se entendemos que um Campo comum se estabelece entre os participantes, fica claro que todos podem se beneficiar do trabalho, mesmo que não constem a sua própria história.</p>

    <p class="section-text">Para além dos preconceitos que rodam as Constelações Familiares, que muitas vezes é descrita, por quem desconhece, como “bruxaria, mágica, macumba”, quando realizada por um profissional capacitado e experiente, os resultados tendem a aparecer, trazendo à consciência compreensões familiares que antes eram ignoradas ou desconhecidas. Por ser um trabalho também psicoterapeutico, não é recomendado que seja feito apenas por curiosidade, e é importante que o participante esteja em acompanhamento psicológico, já que os desdobramentos podem acontecer ao longo de meses após o trabalho.</p>
@else
    <a href="/constelacoes" class="btn btn-theme-color">Leia mais...</a>
@endif
