<p class="section-text">Atualmente chamada de Hellinger sciencia®, a Constelação Familiar, como é comumente conhecida no Brasil, foi desenvolvida por Bert Hellinger. A Constelação Familiar atua na dimensão espiritual do ser humano, o que não quer dizer que atue a partir de uma perspectiva religiosa, mas sim da espiritualidade. Espiritualidade, por definição, significa tudo o que tem por objeto a vida espiritual. Assim, podemos compreender o espiritual como sendo uma dimensão do ser humano, assim como o biológico, o psicológico e o social.</p>

@if (isset($showAll) && $showAll)
    <p class="section-text">O conceito de "campo" da Gestalt terapia, nos fala de um campo que se estabelece entre o organismo e o ambiente. Ao utilizar este conceito na Constelação Familiar, compreendemos que esse campo também se estabelece entre pessoas, ampliando assim a ideia inicial, e oferecendo suporte teórico à Constelação Familiar. No <em>workshop</em> de Constelação Familiar, o participante elege o tema a ser constelado, e escolhe algumas pessoas do grupo para representarem os seus familiares. Por se tratar de um <em>workshop</em>, é comum que as pessoas não se conheçam e, portanto, não possuam informações umas das outras. Podemos assim sugerir que, o "campo" que se estabelece no trabalho de Constelação Familiar é o que permite o acesso a informações tão pessoais, sem que o representante conheça a história da pessoa que está sendo constelada. Este trabalho também pode acontecer no consultório, onde a Constelação Familiar pode ser realizada com bonecos, que serão utilizados como os representantes nas situações que são trazidas pelo cliente.</p>

    <p class="section-text">A diferença do trabalho individual para o trabalho em grupo, é a quantidade de informações que emergem. Pois, como há vários participantes no <em>workshop</em>, temos diferentes pontos de vista de uma mesma situação. Já no trabalho individual, temos apenas o terapeuta e o cliente. De toda maneira, ambos são trabalhos que costumam apresentar resultados satisfatórios no que diz respeito à tomada de consciência que buscamos na psicoterapia. O objetivo da Constelação Familiar é observar a dinâmica dos sistemas familiares, o que nos ajuda a compreender e liberar o fluxo de amor que fica bloqueado quando há algum conflito, exclusão, segredo, rompimento, etc. É importante frisar que o constelador não é aquele que libera o fluxo de amor, pois o trabalho acontece no "campo" que se forma entre todos que participam da constelação. O constelador é aquele que acompanha a evolução do trabalho, contribuindo para que os conflitos venham à tona e possam assim serem compreendidos e reparados, possibilitando a restauração do fluxo de amor.</p>

    <p class="section-text">Todos os participantes do <em>workshop</em> de Constelação Familiar se beneficiam: constelados, representantes e expectadores. Tanto aqueles que participam como representantes, como os que assistem, muitas vezes se identificam com a história que está sendo constelada, e isso auxilia percepções de si, através da dinâmica que está acontecendo. Se entendemos que um "campo" comum se estabelece entre os participantes, fica claro que todos podem se beneficiar do <em>workshop</em>, mesmo que não constelem a sua própria história.
    </p>

    <p class="section-text">
        Quando realizada por um profissional sério e capacitado, os resultados tendem a aparecer, trazendo à consciência compreensões da dinâmica familiar que antes eram ignoradas ou desconhecidas. Por ser um trabalho também psicoterapêutico, não é recomendado que seja feito apenas por curiosidade. É importante que o participante esteja em acompanhamento psicológico, já que os desdobramentos da Constelação Familiar podem acontecer ao longo de meses após o <em>workshop</em>.
    </p>
@else
    <a href="/constelacoes" class="btn btn-theme-color">Leia mais...</a>
@endif
